### ISSUE TITLE
关于计算位置的和替换数据的问题

### ISSUE THREAD

**Issue by DreamForStar** [ZFbaby/ZFSeatsSelection#7]
公司返回的数据没有标识可选,过道的字段 而且是一次把所有的座位数据都在一个列表返回了 怎么处理啊 大神求教了

**Comment by ZFbaby** [comment]
肯定要有标示 你要服务端给你搞




------------------ 原始邮件 ------------------
发件人: DreamForStar <notifications@github.com>
发送时间: 2019年8月2日 10:37
收件人: ZFbaby/ZFSeatsSelection <ZFSeatsSelection@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7)




公司返回的数据没有标识可选,过道的字段 而且是一次把所有的座位数据都在一个列表返回了 怎么处理啊 大神求教了

**Comment by DreamForStar** [comment]
接口用的统一的 现在前端做完了 移动端这边卡住了.说让我们根据每个座位的标号去计算..我还想用你的这个.

**Comment by ZFbaby** [comment]
前端能做说明数据座位有给标示 你在认真对接一下




------------------ 原始邮件 ------------------
发件人: DreamForStar <notifications@github.com>
发送时间: 2019年8月2日 10:41
收件人: ZFbaby/ZFSeatsSelection <ZFSeatsSelection@noreply.github.com>
抄送: ZFbaby <316917975@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7)

**Comment by DreamForStar** [comment]
给了2个位置的信息,一个是绘制底部的所有的,另外是一个返回具体座位信息的

**Comment by DreamForStar** [comment]
能加个微信详细聊下么

**Comment by ZFbaby** [comment]
你对接下我给的那个数据结构 看能不能整理成我这边的结构 前端能做应该也能做的 




------------------ 原始邮件 ------------------
发件人: DreamForStar <notifications@github.com>
发送时间: 2019年8月2日 10:46
收件人: ZFbaby/ZFSeatsSelection <ZFSeatsSelection@noreply.github.com>
抄送: ZFbaby <316917975@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7)

**Comment by ZFbaby** [comment]
我也好久没有看代码的内容了 自己也忘得差不多 好多人之前都有用了我这个模块 你看看代码和数据结构改成你自己想要的就可以




------------------ 原始邮件 ------------------
发件人: DreamForStar <notifications@github.com>
发送时间: 2019年8月2日 10:47
收件人: ZFbaby/ZFSeatsSelection <ZFSeatsSelection@noreply.github.com>
抄送: ZFbaby <316917975@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7)




能加个微信详细聊下么

**Comment by DreamForStar** [comment]
你们数据返回直接返回了每一个列,然后下面是行的信息,没个座位还有标识,我们直接给了6个字段,绘制两层去计算的.愁...
  {
 
        col = 3;
 
        foreignSeatId = "2795$2795_1_3";
 
        graphCol = 6;
 
        graphRow = 1;
 
        loverLeft = "<null>";
 
        row = 1;
 
        state = 0;
 
        type = 0;
 
    }







------------------ 原始邮件 ------------------
发件人: "ZFbaby"<notifications@github.com>; 
发送时间: 2019年8月2日(星期五) 上午10:48
收件人: "ZFbaby/ZFSeatsSelection"<ZFSeatsSelection@noreply.github.com>; 
抄送: "马龙"<673646979@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7)



你对接下我给的那个数据结构 看能不能整理成我这边的结构 前端能做应该也能做的  
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: DreamForStar <notifications@github.com> 
 发送时间: 2019年8月2日 10:46 
 收件人: ZFbaby/ZFSeatsSelection <ZFSeatsSelection@noreply.github.com> 
 抄送: ZFbaby <316917975@qq.com>, Comment <comment@noreply.github.com> 
 主题: 回复：[ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7)

**Comment by ZFbaby** [comment]
这个无非就是你要做个座位索引而已不难






------------------ 原始邮件 ------------------
发件人: DreamForStar <notifications@github.com>
发送时间: 2019年8月2日 10:51
收件人: ZFbaby/ZFSeatsSelection <ZFSeatsSelection@noreply.github.com>
抄送: ZFbaby <316917975@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7)



你们数据返回直接返回了每一个列,然后下面是行的信息,没个座位还有标识,我们直接给了6个字段,绘制两层去计算的.愁... 
   { 
   
         col = 3; 
   
         foreignSeatId = "2795$2795_1_3"; 
   
         graphCol = 6; 
   
         graphRow = 1; 
   
         loverLeft = "<null>"; 
   
         row = 1; 
   
         state = 0; 
   
         type = 0; 
   
     } 
 
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "ZFbaby"<notifications@github.com>;  
 发送时间: 2019年8月2日(星期五) 上午10:48 
 收件人: "ZFbaby/ZFSeatsSelection"<ZFSeatsSelection@noreply.github.com>;  
 抄送: "马龙"<673646979@qq.com>; "Author"<author@noreply.github.com>;  
 主题: Re: [ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7) 
 
 
 
 你对接下我给的那个数据结构 看能不能整理成我这边的结构 前端能做应该也能做的   
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: DreamForStar <notifications@github.com>  
  发送时间: 2019年8月2日 10:46  
  收件人: ZFbaby/ZFSeatsSelection <ZFSeatsSelection@noreply.github.com>  
  抄送: ZFbaby <316917975@qq.com>, Comment <comment@noreply.github.com>  
  主题: 回复：[ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7)

**Comment by ZFbaby** [comment]
我这个是参照猫眼以前的数据结构弄的 我们公司之前座位索引也是自己算




------------------ 原始邮件 ------------------
发件人: DreamForStar <notifications@github.com>
发送时间: 2019年8月2日 10:51
收件人: ZFbaby/ZFSeatsSelection <ZFSeatsSelection@noreply.github.com>
抄送: ZFbaby <316917975@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7)



你们数据返回直接返回了每一个列,然后下面是行的信息,没个座位还有标识,我们直接给了6个字段,绘制两层去计算的.愁... 
   { 
   
         col = 3; 
   
         foreignSeatId = "2795$2795_1_3"; 
   
         graphCol = 6; 
   
         graphRow = 1; 
   
         loverLeft = "<null>"; 
   
         row = 1; 
   
         state = 0; 
   
         type = 0; 
   
     } 
 
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "ZFbaby"<notifications@github.com>;  
 发送时间: 2019年8月2日(星期五) 上午10:48 
 收件人: "ZFbaby/ZFSeatsSelection"<ZFSeatsSelection@noreply.github.com>;  
 抄送: "马龙"<673646979@qq.com>; "Author"<author@noreply.github.com>;  
 主题: Re: [ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7) 
 
 
 
 你对接下我给的那个数据结构 看能不能整理成我这边的结构 前端能做应该也能做的   
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: DreamForStar <notifications@github.com>  
  发送时间: 2019年8月2日 10:46  
  收件人: ZFbaby/ZFSeatsSelection <ZFSeatsSelection@noreply.github.com>  
  抄送: ZFbaby <316917975@qq.com>, Comment <comment@noreply.github.com>  
  主题: 回复：[ZFbaby/ZFSeatsSelection] 关于计算位置的和替换数据的问题 (#7)

**Comment by DreamForStar** [comment]
呃 这个计算我需要在创建2层视图吗? 现在我的想法就是先把下面的网格绘制出来,在把实际的位置绘制出来 您有好的想法么.或者可以提共一个计算索引的demo学习下

**Comment by DreamForStar** [comment]
静下心看了下代码自己莫名的搞好了 还是谢谢 星星已点
